### ISSUE TITLE
Periodicity information gets lost 

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ContactEngineering/SurfaceTopography#184]
I am not sure whether this is a SurfaceTopography or topobank issue.

All measurements in https://contact.engineering/go/v9qwe/ are periodic on topobank, and I think that is how it should be.

But in the container I get by downloading (see snippet below), the measurements are labeled as non-periodic. 

```python
import matplotlib.pyplot as plt
import SurfaceTopography
import numpy as np

container = SurfaceTopography.Container.read_published_container("https://contact.engineering/go/v9qwe/")[0]

pristine = container._topographies[0]
convoluted = container._topographies[1]
print(pristine.is_periodic)
print(convoluted.is_periodic)

print(SurfaceTopography.__version__)
```

**Comment by mcrot** [comment]
The container has a file `meta.yml` with the meta data.
It states that both topographies are periodic, excerpt:
```yaml
topographies:
  - creator:
      name: Lars Pastewka
      orcid: 0000-0001-8351-7336
    data_source: 0
    datafile:
      original: scanned_surf-r_0000_vW8TxEp.txt
      squeezed-netcdf: scanned_surf-r_0000_vW8TxEp-squeezed.nc
    description: Pristine (as synthesized) topography without tip radius artifacts.
    detrend_mode: center
    height_scale: 1.0
    is_periodic: true
    measurement_date: 2017-01-01
    name: scanned_surf-r_0000.txt
    size: !!python/tuple
    - 0.512
    - 0.512
    tags: []
    unit: "\xB5m"
  - creator:
      name: Lars Pastewka
      orcid: 0000-0001-8351-7336
    data_source: 0
    datafile:
      original: scanned_surf-r_0040_qTXHus1.txt
      squeezed-netcdf: scanned_surf-r_0040_qTXHus1-squeezed.nc
    description: Topography scanned with a (virtual) 40 nm tip.
    detrend_mode: center
    height_scale: 1.0
    is_periodic: true
    measurement_date: 2017-01-01
    name: scanned_surf-r_0040.txt
    size: !!python/tuple
    - 0.512
    - 0.512
    tags: []
    unit: "\xB5m"
```
So I guess the function `read_published_container` does not interpret it correctly.
