### ISSUE TITLE
Implement a "read_container" function for reading surfaces

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/SurfaceTopography#65]
During my talk there came up the idea of implementing a "read_container" method in `SurfaceTopography`.

Maybe we should discuss this a bit. So far, the "write container" part is part of the web app code, so writing and
reading is distributed in different projects. It's not trivial to have both in `SurfaceTopography`, because so far the
package has no notion of "surface". 

If we implement the reading here, it should be a bit generic, e.g. concerning the
structure and the field for the datafile names. One reason is that in future there will be two datafiles in the container for one topography: https://github.com/ContactEngineering/TopoBank/issues/579#issuecomment-817136579

The other thing is, that the container could theoretically return topographies for multiple surfaces.
So we should think about the data structure which is returned by "read_container".

Example:
```python
from SurfaceTopography.IO import read_container
surfaces = read_container(datafile_flavor='original')
```

First idea for a generic solution:

`read_container` returns the certain subtree of yaml file `meta.yaml`, all underneath `meta["surfaces"]` which is a list,
with a additional attribute `topography` containing the topography (with correct size etc.). Then all meta data is also available when needed.

# Example

## Original Meta Data YAML file

```yaml
creation_time: '2021-04-12 09:00:53.031039+00:00'
surfaces:
- category: exp
  creator:
    name: "Michael R\xF6ttger"
    orcid: 0000-0002-7111-8570
  description: This surface will be used in a talk.
  is_published: false
  name: Demo Surface
  tags:
  - demo
  topographies:
  - creator:
      name: "Michael R\xF6ttger"
      orcid: 0000-0002-7111-8570
    data_source: 0
    datafile: 10kx_1R_Scale0.462_FIXEDv2p1.asc
    description: ''
    detrend_mode: height
    height_scale: 2.0
    is_periodic: false
    measurement_date: 2019-06-12
    name: 10kx_1R_Scale0.462_FIXEDv2p1.asc
    size: !!python/tuple
    - 2212.10469971
    tags: []
    unit: nm
  - creator:
      name: "Michael R\xF6ttger"
      orcid: 0000-0002-7111-8570
    data_source: 0
    datafile: puncd_dlc_18_5um.003
    description: ''
    detrend_mode: height
    height_scale: 0.11218757475967
    is_periodic: false
    measurement_date: 2021-04-10
    name: puncd_dlc_18_5um.003
    size: !!python/tuple
    - 5000.0
    - 5000.0
    tags: []
    unit: nm
  - creator:
      name: "Michael R\xF6ttger"
      orcid: 0000-0002-7111-8570
    data_source: 0
    datafile: puncd_dlc_20_1um.004
    description: ''
    detrend_mode: height
    height_scale: 0.11508505130463
    is_periodic: false
    measurement_date: 2021-04-10
    name: puncd_dlc_20_1um.004
    size: !!python/tuple
    - 1000.0
    - 1000.0
    tags: []
    unit: nm
versions:
  topobank: 0.10.1
```

# Returned data (Full version)

The data returned by `read_container` would be a list of dicts, where each dict has following format

```yaml
  category: exp
  creator:
    name: "Michael R\xF6ttger"
    orcid: 0000-0002-7111-8570
  description: This surface will be used in a talk.
  is_published: false
  name: Demo Surface
  tags:
  - demo
  topographies:
  - creator:
      name: "Michael R\xF6ttger"
      orcid: 0000-0002-7111-8570
    description: ''
    measurement_date: 2019-06-12
    name: 10kx_1R_Scale0.462_FIXEDv2p1.asc
    topography: <Topography Instance>
  - creator:
      name: "Michael R\xF6ttger"
      orcid: 0000-0002-7111-8570
    description: ''
    measurement_date: 2021-04-10
    name: puncd_dlc_18_5um.003
    topography: <Topography Instance> 
  - creator:
      name: "Michael R\xF6ttger"
      orcid: 0000-0002-7111-8570
    description: ''
    measurement_date: 2021-04-10
    name: puncd_dlc_20_1um.004
    topography: <Topography Instance>
```

# Returned data (Simplified, e.g. by keyword)

The data returned by `read_container` would be a list of topography instances.
